version: '3.8'

services:
  app:
    build: .
    container_name: whisperapi_youtube_transcription
    ports:
      - "5001:5001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped